version: '2'
services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:0.4.0-rc.1
    user: root
    command: serve --location /data --bind 0.0.0.0:7878
    ports:
      - 7878:7878
    volumes:
      - ./oxigraph:/data
