# examples http://localhost:9000/api/statistics/flaechen/R00091?from=1965&to=1987
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT  {
      ?obs a qb:Observation .
      ?obs ?property ?value .
      ?value rdfs:label ?label .
      ?value skos:notation ?notation .
}
WHERE {
    # Specify Class
    ?obs a qb:Observation ;
       ?property ?value.
    # Get Labels and Notations
    OPTIONAL {?value rdfs:label ?label .}
    OPTIONAL { ?value skos:notation ?notation .}

    # Specify properties
    ?obs <http://ld.stadt-zuerich.ch/statistics/property/ZEIT> ?zeitProp;
      <http://ld.stadt-zuerich.ch/statistics/property/RAUM> ?raum;
      <http://ld.stadt-zuerich.ch/statistics/property/GRUPPENCODE1> ?flaeche .

    # Get Notations
    ?raum skos:notation ?raumNotation .
    ?flaeche skos:notation ?flaecheNotation .

    # Only because time is not yet clean bind.
    BIND (xsd:datetime(SUBSTR(str(?zeitProp),STRLEN(str(?zeitProp))-3)) AS ?zeit)

    # Filter per Property
    FILTER (?flaecheNotation IN("BBA1310"))
    ${raum ? 'FILTER (?raumNotation IN (' + (raum.join ? raum.map(v => v.toCanonical()).join() : raum.toCanonical()) + '))' : ''}

    # Filter Time Range
    ${typeof from !== 'undefined'? 'FILTER (?zeit >= xsd:datetime("'+from+'"))':''}
    ${typeof to !== 'undefined'? 'FILTER (?zeit <= xsd:datetime("'+to+'"))':''}
} ORDER BY ?zeit
