name: tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-tests:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        node: [ 18, 20, "lts/*" ]
        package:
          - name: "@kopflos-cms/core"
            path: packages/core
          - name: "@kopflos-cms/express"
            path: packages/express
          - name: "@kopflos-cms/plugin-deploy-resources"
            path: packages/plugin-deploy-resources
          - name: "@kopflos-cms/serve-file"
            path: packages/serve-file
          - name: "@kopflos-cms/hydra"
            path: packages/hydra
          - name: "@kopflos-cms/vite"
            path: packages/vite
          - name: "@kopflos-labs/html-template"
            path: labs/html-template
          - name: "@kopflos-labs/handlebars"
            path: labs/handlebars
          - name: sparql-path-parser
            path: packages/sparql-path-parser
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npx c8 --all --src ${{ matrix.package.path }} --reporter lcovonly --reporter text npm run -w ${{ matrix.package.path }} test
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package.name }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run -ws --if-present build

  smoke-test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-prolog-action@v1
      - uses: lando/setup-lando@v3
        with:
          lando-version: 3.21.2
      - uses: tpluscode/action-lando-start@v0.2.2
        with:
          healthcheck: https://read-the-plaque.lndo.site/plaque/newton-s-apple-tree-monash-university
          timeout: 60000
          ignore-errors: true

      - run: curl https://read-the-plaque.lndo.site/plaque/newton-s-apple-tree-monash-university.html -Ifk

      - run: lando logs
        if: failure()
